[package]
org = "ballerinax"
name = "aws.sqs"
version = "0.1.0"
authors=["ballerina"]
keywords=["IT Operations/Message Brokers", "Cost/Freemium", "Vendor/Amazon"]
repository= "https://github.com/ballerina-platform/module-ballerinax-aws.sqs"
icon="icon.png"
license=["Apache-2.0"]
distribution = "2201.11.0"


[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.sqs-native"
version = "@project.version@"
path = "../native/build/libs/aws.sqs-native-@project.version@.jar"


[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sqs"
version = "@aws.sdk.version@"
path = "./lib/sqs-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "apache-client"
version = "@aws.sdk.version@"
path = "./lib/apache-client-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "auth"
version = "@aws.sdk.version@"
path = "./lib/auth-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-core"
version = "@aws.sdk.version@"
path = "./lib/aws-core-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-json-protocol"
version = "@aws.sdk.version@"
path = "./lib/aws-json-protocol-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums"
version = "@aws.sdk.version@"
path = "./lib/checksums-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums-spi"
version = "@aws.sdk.version@"
path = "./lib/checksums-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "endpoints-spi"
version = "@aws.sdk.version@"
path = "./lib/endpoints-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth"
version = "@aws.sdk.version@"
path = "./lib/http-auth-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws"
version = "@aws.sdk.version@"
path = "./lib/http-auth-aws-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-spi"
version = "@aws.sdk.version@"
path = "./lib/http-auth-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-client-spi"
version = "@aws.sdk.version@"
path = "./lib/http-client-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "identity-spi"
version = "@aws.sdk.version@"
path = "./lib/identity-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "json-utils"
version = "@aws.sdk.version@"
path = "./lib/json-utils-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "metrics-spi"
version = "@aws.sdk.version@"
path = "./lib/metrics-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "profiles"
version = "@aws.sdk.version@"
path = "./lib/profiles-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "protocol-core"
version = "@aws.sdk.version@"
path = "./lib/protocol-core-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "regions"
version = "@aws.sdk.version@"
path = "./lib/regions-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries"
version = "@aws.sdk.version@"
path = "./lib/retries-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries-spi"
version = "@aws.sdk.version@"
path = "./lib/retries-spi-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sdk-core"
version = "@aws.sdk.version@"
path = "./lib/sdk-core-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "third-party-jackson-core"
version = "@aws.sdk.version@"
path = "./lib/third-party-jackson-core-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "utils"
version = "@aws.sdk.version@"
path = "./lib/utils-@aws.sdk.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpcore"
version = "@apache.httpcore.version@"
path = "./lib/httpcore-@apache.httpcore.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpclient"
version = "@apache.httpclient.version@"
path = "./lib/httpclient-@apache.httpclient.version@.jar"

[[platform.java21.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "@reactivestreams.version@"
path = "./lib/reactive-streams-@reactivestreams.version@.jar"