name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
          - STAGE
          - DEV
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: 2201.2.1

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Build Module Examples
      - name: Ballerina Examples Build
        run: chmod +x ./examples/build.sh && ./examples/build.sh build
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Push to Ballerina Staging Central
      - name: Push to Staging
        if: github.event.inputs.bal_central_environment == 'STAGE'
        run: bal push
        working-directory: ./ballerina
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Push to Ballerina Dev Central
      - name: Push to Dev
        if: github.event.inputs.bal_central_environment == 'DEV'
        run: bal push
        working-directory: ./ballerina
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm
